model:
    family: diffusion_qwen2
    n_dims: 20
    n_embd: 256
    n_head: 8
    n_layer: 12
    n_positions: 256

training:
    task: "linear_regression"
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 5e-5
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            end: 20
            inc: 1
            interval: 100
            start: 5
        points:
            end: 41
            inc: 1
            interval: 100
            start: 10

out_dir: "logs/in-context-learning"

wandb:
    enabled: true
    project: icl-dllm
    entity: jaredanjerry-southern-university-of-science-technology
    notes: "Base configuration"
    name: "linear_regression"
    log_every_steps: 10